# CLOY Processing

This notebook is for you to work with the CLOY data folder.

## 1. Turning every CLOY thread into a vector of words

### A. Loading all threads

First, I want to explore looking into one thread in the CLOY file.

In [120]:
import json

with open("RedditExplorer/cloy_chronological.jsonl") as f:
    first_line = f.readline()

thread = json.loads(first_line)

print(thread.keys())
type(thread)

dict_keys(['post_id', 'timestamp', 'author', 'subreddit', 'title', 'selftext', 'url', 'score', 'permalink', 'comments'])

dict

I dump all threads into a list for simplicity later

In [121]:
threads = []

with open("RedditExplorer/cloy_chronological.jsonl") as f:
    for line in f:
        threads.append(json.loads(line))
type (threads)

list

I look into a complete thread.

In [ ]:
#threads[4]

{'post_id': 'fj5byj',
 'timestamp': 1584294837,
 'author': 'titania73',
 'subreddit': 'CrashLandingOnYou',
 'title': 'Why I think we all need a second season of CLOY. (Spoilers)',
 'selftext': 'I binged crash landing on you this week and can’t stop thinking about this show! I love the characters, the story line, and how unique it is compared to a lot of other dramedies I’ve watched. But I have to admit that I was a bit disappointed with the ending. This seems to be an unpopular opinion as a lot of fans online say that it ended well and a second season may ruin it. They found their way back to each other and that’s what matters. \n\nI disagree. I can’t believe that this is the best future we get for these two characters. Seeing each other two weeks a year may be fine for now, but how is that a fair relationship for either of them long term? So much happens in a year - how can two weeks without any other communication be enough? We see time and time again how much they mean to each other and how their lives get better in a million tiny ways when they are together.\n\nThere’s a lot more story to tell for the main couple and for the supporting characters. I hope that we get to see a second season where they end up choosing each other and actually build a life together. \n\n\nJeong Hyeuk’s mom really wants to see her son happy, and I’d like to see how she deals with her son being alone all the time. Will his dad pressure him into another marriage? \n\nWill Seri need to date in public again, and will that strain their relationship? \n\nI’d love to see Dan find love again and all the shenanigans that would go into her mother trying to get a new husband. \n\nCould the soldiers in the 5th brigade find love too? \n\nWhat do you guys think? Do you guys want to see another season or do you think the story is perfect as is? What would you like to see in season2?',
 'url': 'https://www.reddit.com/r/CrashLandingOnYou/comments/fj5byj/why_i_think_we_all_need_a_second_season_of_cloy/',
 'score': 20,
 'permalink': 'https://reddit.com/r/CrashLandingOnYou/comments/fj5byj/why_i_think_we_all_need_a_second_season_of_cloy/',
 'comments': [{'comment_id': 'fkkzuim',
   'parent_id': 't3_fj5byj',
   'author': '[deleted]',
   'comment_body': 'I think Season 1 ended perfectly in terms of answering my burning questions. Given the historical context of the drama, I think this is really the best we could’ve gotten. \n\nI’ve been hearing this fan theory float around — that RJH may defect to the South after his parents die, so as to not put them at harm. And knowing that, frankly, is enough for me. Of course, I would love to see something definite, such as RJH’s dream — of having twins — manifest. \n\nBut yes, I would love to watch these characters again. Just thinking realistically. Back to binging CLOY clips. (Should I rewatch???) :)',
   'score': 17,
   'created_utc': 1584295449,
   'replies': [{'comment_id': 'fkl4fle',
     'parent_id': 't1_fkkzuim',
     'author': 'titania73',
     'comment_body': 'That’s a good theory - I haven’t come across that one! Things like that will make it easier to bear if that’s all we get. \n\nThe chemistry between the actors is unbelievable and I would be okay watching anything with these two together lol.',
     'score': 2,
     'created_utc': 1584298257},
    {'comment_id': 'flhisvi',
     'parent_id': 't1_fkkzuim',
     'author': 'phalange94',
     'comment_body': "I agree - it ended perfectly and was a great compromise for Seri and RJH. If somehow RJH left NK, I think that would've been way too happy of a situation and would have implications to his family. We would all love to see them see together and life build out, but apart from that, it would be hard to have a good storyline for season 2.\n\nThe one thing that confused me was when Dan's mom spoke to RJH's mom about how their kids love someone more than their own life and RJH's mom understood. I thought based on this interaction, it would have made RJH's mom do more to get her son out of NK.\n\nI just wished the last episode had more interactions between RJH and Seri!",
     'score': 6,
     'created_utc': 1585163463}]},
  {'comment_id': 'fkq53pe',
   'parent_id': 't3_fj5byj',
   'author': 'bulleuse',
   'comment_body': 'This drama ends perfectly. You know what is season 2 ? Reunification between both Koreas. This series screams reunification.',
   'score': 8,
   'created_utc': 1584430904},
  {'comment_id': 'fl00wf7',
   'parent_id': 't3_fj5byj',
   'author': 'i_live_on_dream_st',
   'comment_body': 'Do you guys think we’ll get a second season?? I’m really praying for it!!!',
   'score': 3,
   'created_utc': 1584687083},
  {'comment_id': 'fll1kl6',
   'parent_id': 't3_fj5byj',
   'author': 'usernameisinvaliderr',
   'comment_body': 'Yes either reunification or RJH’s parents dying and him defecting. But yes just a shot of them with twins ten years in the future would be SO satisfying. American movies would definitely do that. I guess Korean tv/movies are different? This is my first Korean one too. Although I’m not sure if I’ll watch more. This was perfect and I don’t want to ruin the memory by watching something bad next.',
   'score': 5,
   'created_utc': 1585251904},
  {'comment_id': 'flrw9lj',
   'parent_id': 't3_fj5byj',
   'author': 'Joeytorreo',
   'comment_body': "100% agreed with all the points you made. I didn't like the ending. After all they went through I dont know how they can just settle seeing each other two weeks a year.",
   'score': 3,
   'created_utc': 1585429194},
  {'comment_id': 'fmn3gsn',
   'parent_id': 't3_fj5byj',
   'author': 'AlluringAvocado',
   'comment_body': "While I would love a second season, I have a feeling it wouldn't be as exciting as Season 1. Maybe a special episode that shows what they're up to 5 or 10 years later. :) I think that'd be more likely to happen.\n\nI don't believe Seri and RJH would only see each other for 2 weeks a year. Seo Dan was able to study music in Russia for a long period of time, so maybe he can do something similar. As others have mentioned, RJH probably can't defect right now because of his parents, but once they pass, he'd probably be able to.\n\nPlus, fate is on their side!! I'm sure this was just a temporary solution. They'll work something out.\n\nI can't believe how invested I am in fictional characters.",
   'score': 3,
   'created_utc': 1586217407},
  {'comment_id': 'fxko6v2',
   'parent_id': 't3_fj5byj',
   'author': 'SunnyCity1',
   'comment_body': "If they do a season two they need a sex scene. Just saying.\n\nPartially because I'm a Westerner and this is what I'm used to. Mainly because I want to see Hyun Bin shirtless :D",
   'score': 1,
   'created_utc': 1594417263}]}

It seems like comments are under `comment_body`, and under each comment there is also `replies`. More comments are under `comment_body` under `replies` under comments.

### B. Getting all comments

This function keeps going until it reaches a comment that does not have `replies`. This function also gets all the comments nested under one comment.

In [123]:
def get_comment_sentence (comment):
    sentence = comment["comment_body"]
    if "replies" in comment:
        for reply in comment["replies"]:
            sentence = sentence + " "+get_comment_sentence(reply)

    return sentence

### C. Turn one entire thread into one string

The question asks for main post, that means I also need to extract the `title` and `selftext`.

In [124]:
def get_thread_sentence(thread):
    sentence = thread["title"] + " " + thread["selftext"]

    for comment in thread["comments"]:
        sentence += " " + get_comment_sentence(comment)

    return sentence

Let's see if this works on the first thread.

In [ ]:
#print(get_thread_sentence(threads[1]))

ok, let’s get this started! What are your thoughts about the show? I haven’t seen a kdrama for the longest time and it was actually my dad who chose to stream CLOY on Netflix. He stopped watching after the second episode but I went on after immediately falling in love with the leads. Hyun Bin is just so charismatic as Capt. Ri Jeong Hyeok and Son Ye-jin is perfect as Yoon Se-ri. She’s definitely got the rom-com and drama genre down pat! I also loved Capt. Ri’s squad, most especially Pyo Chi Su ☺️ (we can probably talk about individual characters next time).

CLOY tackled politics, drama and deception, family issues, friendships - and best of all, pure unconditional love, love brought about by fate - all in one highly entertaining and well-written package.

I’m planning on doing a rewatch soon, when I get a chance! i'm so emotionally drained and exhausted from being in awe of this show even though i finished watching 2 weeks ago. my brain doesn't work cuz i'm thinking about CLOY and my favorite part of it other than the couple is that the women have really 3D roles... like Seri can cry nonstop but you still know she a boss. Did you have a favorite episode? Mine would have to be ep. 9 ☺️ I have not finished it yet, but I already see your point. Episode 9 is when you feel things are going to end happily. Also the stuff in RJH;s parents' home is priceless. I love this show. I stumbled across it on Netflix, gave it a try, and fell in love. I finished it this morning and already miss it. I love Yoon Se-Ri and Jeong Hyeok and nearly all of the other characters. I was so happy with the ending. I’ve added two more kdramas to my Netflix list. Which ones! Itaewon Class, Chocolate, When the Camellia Blooms Thank you :) I'm currently obsessed with Hyun Bin. I've never watched Korean dramas, the most asian movie I ever got to watch was the one by Daniel Henney! And this show comes on Netflix and I'm awed. I've literally added so many K dramas to my list now!

This is a well rounded drama- irrespective of language or Korean drama wise. It had all characters play a role and there's comic angle for some characters which is just so much fun to watch! They really did a great job with this one. ❤️ Good on ya, girl! And yes I agree, it’s hard not to fall in love with Hyun Bin. You should probably check him out in Secret Garden too.

The writing on this show, to me, is practically flawless. And the ending was definitely satisfying. I've already started My lovely Sam Soon. Secret garden is next ❤️ thanks for the recommendation 🥰 You’re welcome! 😊 Alright so, a week ago my partner went back to his family home for holiday, we recently moved in a big house and I was terrified being alone in there, super anxious. The first night was awful as I was stressing the sh*t out of me anytime I would hear a sound.. Even the wind was an enemy. So I went lurking on Netflix about to watch a good old How I Met Your Mother episode trying to ease my pain when I stumble into CLOY.. I never watched a Korean Drama but the storyline seemed interesting and I really needed something to keep me occupy so I played it....

Oh my lord

Did I even sleep more than 5hours per night that week ? I’m not sure. Did I call my mother once ? I’m not sure. I got literally sucked by the show. I would watch it in the morning while drinking my coffee, then in the tube on my way to work, then on my break, then in the tube again and straight on tv with my dinner at home. At work I couldn’t stay focus at time being too busy wondering what’s gonna happen next and If I was talking to my colleague it would only be to spread a strong and passionate propaganda about the show.. I started texting my partner less, actually I started texting everyone less lol.

I still not fully comprehend how a show could make me cry in a crowded tube to then make me laugh a minute later making me look like an absolute lunatic.

Everything was perfect, rarely did I watch a show where the side characters were as charismatic and as important for me as the main ones.

When you think that each episode was around 1h20 in length which round it up to 35hours or so in total. You wonder... HOW DID THEY MANAGE TO MAKE EVERY DAMN SECONDS SO SPECIAL???? I’m still in awe...

I was so grateful for the show to tickle my favourite subjects with such delicacy; Romance, History and Comic. Surely in general I can find Romance and History genre or Romance and Comic genre in a movie or a show but did I ever cry laugh and learn all at the same time?
Being able to discover more about Korea’s lifestyle and the sinkhole there is between the South and the North was a blessing. I think as much for us than for the Korean themselves.
Every time Seri would mention the reunification as “you can get your gift when we reunify” I’d be thinking BUT THERE IS NO REUNIFICATION SO WHEN WILL THEY SEE EACHOTHER AGAIN ? HOW IS HE GONNA MEET IS FAVOURITE KDRAMA ACTRESS ? WHAT WILL THE CREATOR DO TO MAKE THEM MEET AGAIN WHILE STILL BEING ACCURATE WITH THE PRESENT POLITICS????

They figured a way and they smashed it.


The day my partner came back so 6 days later, I was watching the last episode. By the time he arrived I had 1minute and 20secondes left. I already saw the beautiful last scene where our lover find eachother again and I was pretty proud of myself for managing it so well.. not event crying! Then, after being reunited with my own lover I tell him “ hey I have one minute left on my show do you mind if I watch?” And he was like “yeah sure”

I put the show back on and really the last minute was literally just the end credits. However that’s when I understood it was over like really over.. I froze for a second and bursted into tears, threw myself in my partners arms, yelling nonsense... I wonder if he thought it was because I missed him haha. After that I told him I was in a mourning period and out of respect for the show, begged him to not propose me to watch anything else for the coming week...

That’s how much I liked it.

Now my goal is to spread the love for CLOY to the people around me hoping they will give it a chance so they can become lunatics with me :) it's my first Kdrama. I'm telling everyone to watch it. It's so well-written, production value is high, and all the characters are given a moment to shine so there's amazing character development arc. Also, I now have a huge crush on HB. I cried a lot. Period I absolutely adore CLOY. This was my first time watching a kdrama but it was an amazing first experience. (I’m watching Something In The Rain now with the same female lead.) I fell in love with all the characters in CLOY and the emotional development of the characters was so fulfilling to see. I usually don’t like endings of shows like this because I always feel like I want to see more but I was very satisfied with how they wrapped up the series. Overall, a great watch, super well written, phenomenal acting and casting. I will definitely recommend it to everyone I know! Anyone notice that  Park Kwang-beom had a noticeably less amount of lines in the show later on? I’d like to think maybe because his character was the handsome yet shy type, the one who doesn’t even realize how good-looking he is and is so humble about it...especially when they got to Seoul. When they were back in NoKor and was Capt. Ri’s sort of right hand he had more exposure and dialogue... Interesting take! thanks! I wouldn’t want to think the writers just got lazy 😆 I thought his character was the strong, silent type. He was always calmer and quieter than the rest of the group. cloy the first kdrama i watched and i love it!! my wife kept asking me to watch kdrama and i'm like "i don't want romance, just action or sci-fi." so past months they kept watching em and i'd be on programming or some hobby thing until this lockdown. ok fine, i'll try em.  watched a fight one and that was awesome, so tried this and i just cry or weep - i'm a mess. my
kids laugh cause i barely cry elsewise but this show wrecked me. now it's all i wanna watch. i'll be sad when it's over, and Ri is like a role model now - how to be that awesome superhero man.

### D. Turn the string into words using textblob

In [48]:
from textblob import TextBlob

I tokenize each thread into words.

In [55]:
thread_words = []
for thread in threads:
    text = get_thread_sentence(thread)
    tblob = TextBlob(text)
    thread_words.append(tblob.words)

In [56]:
thread_words[0]

WordList(['Crash', 'Landing', 'On', 'You', 'has', 'been', 'created', 'deleted'])

I realize that the current code makes my words case sensitive. Therefore I lowercase the texts.

In [57]:
thread_words = []
for thread in threads:
    text = get_thread_sentence(thread)
    tblob = TextBlob(text.lower())
    thread_words.append(tblob.words)

In [58]:
thread_words[0]

WordList(['crash', 'landing', 'on', 'you', 'has', 'been', 'created', 'deleted'])

### E. Create the vocabulary of all unique terms

I am a bit stuck here. I don't really know how to create the vacabulary, and I am not sure how to capture unique terms. I googled and learned about `set`

In [59]:
vocab = set()
for words in thread_words:
    for word in words:
        vocab.add(word)

In [ ]:
vocab = sorted(list(vocab))
#print(vocab[5505:7000])

['cheeky', 'cheer', 'cheered', 'cheerful', 'cheerier', 'cheering', 'cheers', 'cheers🙂', 'cheese', 'cheesey', 'cheesier', 'cheesiest', 'cheesling', 'cheesy', 'chef', 'chefs', 'cheka', 'chekhov', 'chel', 'chemical', 'chemicals', 'chemistrious', 'chemistrt', 'chemistry', 'chemistry…', 'chemistry❤️', 'chemisty', 'cheo', 'cheok-gang', 'cheol', 'cheol-gang', 'cheol-kang', 'cheol-woong', 'cheolgang', 'cheols', 'cheon', 'cheon-sang', 'cheong', 'cheool-gang', 'cherish', 'cherished', 'cherishing', 'cherry', 'chess', 'chest', 'chested', 'chests', 'cheul', 'cheul-gang', 'chew', 'chewing', 'chews', 'chez', 'chf', 'chhod', 'chi', 'chi-hwa-seon', 'chi-so', 'chi-soo', 'chi-su', 'chi-sui', 'chibi', 'chibis', 'chic', 'chicago', 'chick', 'chicken', 'chickens', 'chicks', 'chiding', 'chief', 'chihwaseon', 'child', 'child-like', 'childbirth', 'childhood', 'childhood/adolescence', 'childhood/teen', 'childish', 'childishly', 'childlike', 'children', 'childs', 'chili', 'chill', 'chillin', 'chilliness', 'chilling', 'chillon', 'chills', 'chilly', 'chilseok', 'chime', 'chimes', 'chiming', 'chin', 'chin-goo', 'china', 'china-north', 'china/indonesia/syria', 'chinatown', 'chinaware', 'chinee', 'chines', 'chinese', 'chinese-korean-japanese', 'chinese-nk', 'chinese-relations', 'chinese-style', 'chinese/english/malay', 'chinese/japanese', 'chinese/korean', 'chinggu', 'chingu', 'chip', 'chipped', 'chippy', 'chips', 'chirping', 'chisel', 'chiseled', 'chiseok', 'chisoi', 'chisu', 'chiu', 'chiuso', 'chivalrous', 'chivalry', 'chloe', 'chng.it/bvgrrmg5xh', 'chng.it/djwzqbjdwt', 'cho', 'cho-cheol', 'chock-full', 'chocked', 'chocolate', 'chocolates', 'choe', 'choel', 'choel-gang', 'choen', 'choeol', 'choi', 'choice', 'choice/say', 'choices', 'choirs', 'choisi', 'choix', 'choke', 'choked', 'chokehold', 'choking', 'chol', 'chol-pak', 'cholera', 'chomping', 'choo', 'choong-ryeol', 'choose', 'choose/vote', 'chooses', 'choose🙈', 'choosing', 'chopard', 'chopin', 'chopped', 'choppy', 'chops', 'chopsticks', 'chorar', 'chord', 'chords', 'choreographed', 'choreography', 'chores', 'chorus', 'chose', 'chosen', 'choses', 'chowing', 'chris', 'christ', 'christian', 'christianity', 'christians', 'christmas', 'christmas/new', 'christmastime', 'chromite', 'chronic', 'chronical', 'chronically', 'chronicals', 'chroniclas', 'chronicled', 'chronicles', 'chronological', 'chronologically', 'chronology', 'chu', 'chubbier', 'chubby', 'chuck', 'chuck-full', 'chucked', 'chuckle', 'chuckled', 'chuckles', 'chuckle🤣', 'chuckling', 'chug', 'chugged', 'chukahamnida', 'chukha', 'chukhamnida', 'chul', 'chul-gang', 'chul-soo', 'chulsoo', 'chump', 'chung', 'chungcheong', 'chungju', 'chungmuro', 'chungmuro+hallyu', 'chungmurro', 'chungsa', 'chungŭp-pyŏngsa', 'chunk', 'chunks', 'chunky', 'chunsa', 'church', 'churches', 'church😂', 'churning', 'chuseok', 'chute', 'cia', 'cid=jen', 'ciempre', 'cigar', 'cigarette', 'cigarettes', 'cimgr.clozette.co/cimg/f_jpg', 'cimo', 'cinamatic', 'cinder', 'cinderella', 'cinema', 'cinema/tv', 'cinematic', 'cinematically', 'cinematographer', 'cinematography', 'cinematoraphy', 'cioppino', 'circle', 'circles', 'circling', 'circular', 'circulate', 'circulating', 'circumspect', 'circumstance', 'circumstances', 'circus', 'cite', 'cite_note-2', 'cite_note-census2015-3', 'cited', 'cites', 'cities', 'citing', 'citizen', 'citizens', 'citizenship', 'citizenships', 'citizens…', 'city', 'city/town', 'cityoffandoms-yjn20', 'cityscapes', 'civil', 'civilian', 'civilians', 'civilians/soldiers', 'civilisation', 'civilization', 'civilized', 'civvie', 'cj', 'cjcaldea', 'cjenm', 'cjw', 'ck', 'cka', 'cl', 'cla', 'clad', 'claim', 'claimed', 'claiming', 'claims', 'clair', 'claire', 'clairement', 'clam', 'clam-party', 'clam-soju', 'clambake', 'clamor', 'clamp', 'clamps', 'clams', 'clams/soju', 'clamshells', 'clan', 'clandestine', 'clans', 'clapping/evoking', 'claps', 'clare', 'clarence', 'clarification', 'clarifications', 'clarified', 'clarifies', 'clarify', 'clarifying', 'clarify…', 'clarinet', 'clarity', 'clark', 'clarksville', 'clash', 'clashes', 'clasped', 'class', 'classes', 'classic', 'classical', 'classics', 'classier', 'classification', 'classified', 'classify', 'classmate', 'classmates', 'classroom', 'classy', 'claude', 'clause', 'claustraphobia', 'clay', 'clayholic', 'cld', 'clean', 'cleaned', 'cleaner', 'cleaners', 'cleanest', 'cleaning', 'cleanly', 'cleans', 'cleanse', 'cleansed', 'cleanser', 'cleansers', 'cleansing', 'clear', 'clear-cut', 'clear-headed', 'clearance', 'cleared', 'clearer', 'clearing', 'clearly', 'clears', 'cleary', 'cleavage', 'clench', 'clenched', 'clenching', 'cleopatra', 'clerk', 'clever', 'clever/playful', 'cleverclassic.com/trending/korea-differences-tw', 'cleverer', 'cleverly', 'cleverness', 'clica', 'cliche', 'cliched', 'cliches', 'cliché', 'clichéd', 'clichés', 'click', 'click-bait', 'click_key=780772dfc8c08fb91093fc76df67e0e39e44691b', 'click_sum=d259656a', 'clickbait', 'clickbaity', 'clicked', 'clicking', 'clicks', 'client', 'clients', 'cliff', 'cliffhanger', 'cliffhangers', 'climactic', 'climate', 'climatic', 'climatures', 'climax', 'climax…', 'climb', 'climbed', 'climbing', 'clincher', 'cling', 'clinging', 'clings', 'clingy', 'clinic', 'clinically', 'clins', 'clint', 'clip', 'clip=81019927', 'clip=81280619', 'clip=81406157', 'clipped', 'clipping', 'clips', 'clique', 'cloak', 'clock', 'clocked', 'clocking', 'clocks', 'clomping', 'clone', 'clooney', 'close', 'close-run', 'close-up', 'close-ups', 'close/fine', 'closed', 'closed-mouth', 'closed-off', 'closeee', 'closely', 'closeminded', 'closeness', 'closer', 'closes', 'closest', 'closest-sounding', 'closet', 'closeted', 'closeup', 'closeups', 'closing', 'closure', 'closures', 'clot', 'cloth', 'cloth-wrapped', 'clothes', 'clothes/have', 'clothesline', 'clothes😂', 'clothing', 'cloths', 'clou', 'cloud', 'clouded', 'clouds', 'cloudy', 'clout', 'clown', 'clownish', 'cloy', "cloy'ing", 'cloy-2', 'cloy-era', 'cloy-generated', 'cloy-level', 'cloy-lovers', 'cloy-mr', 'cloy-related', 'cloy-shaped', 'cloy-sitr', 'cloy-size', 'cloy-specific', 'cloy-style', 'cloy-th', 'cloy-themed', 'cloy-verse', 'cloy-watcher', 'cloy-watchers', 'cloy-withdraw', 'cloy-world', 'cloy-zens', 'cloy.i', 'cloy.♥️', 'cloy.😂', 'cloy.😍', 'cloy.🥰', 'cloy/binjin', 'cloy/dinner', 'cloy/hb', 'cloy/hyun', 'cloy/riri/binjin', 'cloy/yejin/hyun', 'cloy/yoon', 'cloy2', 'cloyand', 'cloydom', 'cloyeawer', 'cloyepisode17', 'cloyers', 'cloyfan93', 'cloyholic', 'cloyholics', 'cloying', 'cloyness', 'cloys', 'cloyworld', 'cloy´s', 'cloy…', 'cloy✌️', 'cloy❤', 'cloy❤️♥️', 'cloy😩😂', 'cloy😭', 'cloy🤣', 'cloy🥰', 'cloy🥺', 'cloy🫰🏽', 'club', 'club…', 'clue', 'clued', 'clueless', 'clueless/innocent', 'cluelessness', 'clues', 'clumsy', 'clung', 'clunky', 'clutch', 'clutched', 'cluttered', 'clutz', 'cly', 'clyde', 'cm', 'cmiiw', 'cmmanded', 'cmp=share_iosapp_other', 'cmpid=art_welder_dias', 'cn', 'cnn', 'co', 'co-actors', 'co-ask', 'co-exist', 'co-habitation', 'co-heroes', 'co-lead', 'co-opted', 'co-production', 'co-star', 'co-starred', 'co-starring', 'co-stars', 'co-worker', 'co-workers', 'co-written', 'coach', 'coaching', 'coal', 'coals', 'coarse', 'coast', 'coastal', 'coaster', 'coasters', 'coastguard', 'coat', 'coat/shoulder', 'coating', 'coats', 'coaxing', 'coca', 'cock', 'cockroach', 'cocktail', 'cocktails', 'cocky', 'coco', 'code', 'coded', 'codenames', 'codes', 'code📙', 'coerce', 'coerced', 'coercing', 'coercive', 'coeur', 'coex', 'coffee', 'coffee-making', 'coffeepot', 'coffees', 'coffee…', 'coffin', 'cognac', 'cognitive', 'cogs', 'cogwheel', 'cohabitating', 'cohen', 'coherent', 'cohesion', 'cohesive', 'cohoots', 'cohort', 'cohorts', 'coiffed', 'coiffure', 'coin', 'coincide', 'coincided', 'coincidence', 'coincidence/fate', 'coincidences', 'coincidental', 'coincidentally', 'coincides', 'coined', 'coisa', 'col', 'cola', 'cold', 'cold-blood', 'cold-blooded', 'cold-hearted', 'cold/bitchy', 'cold/robotic', 'colder', 'coldest', 'coldhearted', 'coldly', 'coldness', 'coldplay', 'cold…', 'cold❤️', 'colin', 'collab', 'collabing', 'collaborate', 'collaborated', 'collaborating', 'collaboration', 'collaborations', 'collage', 'collapse', 'collapsed', 'collapses', 'collapses…', 'collapsing', 'collar', 'collared', 'collars', 'colleague', 'colleagues', 'collect', 'collected', 'collectible', 'collectibles', 'collecting', 'collection', 'collections', 'collections=2288654', 'collective', 'collectively', 'collectivist', 'collectivization', 'collector', 'collectors', 'collects', 'college', 'college-educated', 'college-going', 'collegiate', 'collide', 'colliding', 'collins', 'collision', 'colloenl', 'collonel', 'colloner', 'colloquial', 'colombian', 'colonel', 'colonels', 'colonial', 'colonized', 'color', 'color=072', 'colorado', 'coloratura', 'colorblock', 'colored', 'colorful', 'colors', 'colour', 'coloured', 'colourful', 'colouring', 'colours', 'columbia', 'columbo', 'column', 'coly', 'com', 'coma', 'comb', 'combat', 'combative', 'combativeness', 'combination', 'combinations', 'combine', 'combined', 'combines', 'combining', 'combo', 'come', 'comeback', 'comebacks', 'comedian', 'comedic', 'comedic/goofy', 'comedically', 'comedies', 'comedies/dramas', 'comedies/romance', 'comedy', 'comedy-action-crime', 'comedy/drama', 'comedy/dramedy', 'comeo', 'comer', 'comerades', 'comers', 'comes', 'comesi', 'comfort', 'comfort-watch', 'comfort/feel', 'comfortable', 'comfortables', 'comfortably', 'comforted', 'comforting', 'comforts', 'comfy', 'comi', 'comic', 'comical', 'comics', 'coming', 'comipling', 'command', 'commanded', 'commander', 'commanders', 'commanding', 'commandos', 'commands', 'comme', 'commemorate', 'commemorated', 'commemorates', 'commemorative', 'commence', 'commenced', 'commencing', 'commend', 'commendable', 'comment', 'comment/discuss', 'comment/heard', 'comment=21881614', 'commentaire', 'commentaries', 'commentary', 'commentary…a', 'commentator', 'commentators', 'commented', 'commenter', 'commenters', 'commenti', 'commenting', 'commentors', 'commentry', 'comments', 'comments…', 'commeraderie', 'commerades', 'commerce', 'commercial', 'commercialized', 'commercially', 'commercials', 'commerical', 'comming', 'commiserate', 'commissar', 'commissars', 'commission', 'commissioned', 'commit', 'commiting', 'commitment', 'commitments', 'commits', 'committed', 'committee', 'committing', 'committments', 'commmented', 'commodity', 'commodore', 'common', 'commonalities', 'commoner', 'commoners', 'commonly', 'commonplace', 'commontourist6415', 'comms', 'communal', 'communicate', 'communicate/meet', 'communicated', 'communicates', 'communicating', 'communication', 'communications', 'communicator', 'communism', 'communist', 'communists', 'communities', 'community', 'community/country', 'community…', 'commute', 'commutes', 'commuties', 'commy', 'como', 'comp', 'compaaring', 'compan', 'companies', 'companion', 'companions', 'companionship', 'company', 'comparable', 'comparables', 'comparably', 'comparatively', 'compare', 'compared', 'compares', 'comparing', 'comparison', 'comparisons', 'compartir', 'compass', 'compassion', 'compassionate', 'compassion💘', 'compatibility', 'compatible', 'compatriots', 'compelled', 'compelling', 'compendium', 'compensate', 'compensation', 'compersion', 'competant', 'compete', 'competence', 'competent', 'competing', 'competition', 'competition/sports/olympics', 'competitions', 'competitive', 'competitive/jealous/pouty', 'competitiveness', 'competitor', 'competitors', 'compilation', 'compilations', 'compile', 'compiled', 'compiling', 'complacency', 'complain', 'complained', 'complaing', 'complaining', 'complains', 'complaint', 'complaints', 'complaint…', 'complement', 'complemented', 'complete', 'completed', 'completely', 'completely/wants', 'completeness', 'completes', 'completey', 'completing', 'completly', 'complex', 'complexities', 'complexity', 'compliance', 'compliant', 'complicate', 'complicated', 'complicated/clever', 'complicating', 'complication', 'complications', 'complicit', 'complied', 'compliment', 'complimentary', 'complimented', 'complimenting', 'compliments', 'comply', 'component', 'components', 'compose', 'composed', 'composer', 'composers', 'composes', 'composing', 'composition', 'compositions', 'composure', 'compound', 'compounded', 'comprehend', 'comprehending', 'comprehensible', 'comprehensive', 'comprends', 'comprising', 'compromise', 'compromised', 'compromises', 'compromising', 'compulsion', 'compulsory', 'computer', 'computer/phone', 'computers', 'comrade', 'comraderie', 'comradery', 'comrades', 'comradeship', 'comradrie', 'coms', 'comunicado', 'comédie', 'com…', 'con', 'con-man', 'con-mannn', 'concealed', 'concealer', 'concealing', 'concede', 'conceded', 'conceited', 'conceivably', 'conceive', 'conceived', 'concentrate', 'concentrated', 'concentrating', 'concentration', 'concentré', 'concept', 'conception', 'concepts', 'conceptualizing', 'concerm', 'concern', 'concerned', 'concerned/horrified', 'concerning', 'concerns', 'concert', 'concert/musical', 'concerto', 'concertos', 'concerts', 'concession', 'conclude', 'concluded', 'concludes', 'concluding', 'conclusion', 'conclusions', 'conclusive', 'concrete', 'concur', 'concussions', 'condemned', 'condensed', 'condescending', 'condescension', 'condition', 'conditional', 'conditioned', 'conditioner', 'conditions', 'conditions…', 'condo', 'condolence', 'condoms', 'condone', 'conduct', 'conducted', 'conducting', 'conervative', 'confectioneries', 'confederacy', 'confederate', 'conference', 'conferences', 'confess', 'confessed', 'confesses', 'confessing', 'confession', 'confessions', 'confetti', 'confidant', 'confide', 'confided', 'confidence', 'confident', 'confidential', 'confidentiality', 'confidentially', 'confidently', 'confides', 'confinement', 'confining', 'confirm', 'confirmation', 'confirmations', 'confirmed', 'confirming', 'confirms', 'confiscated', 'confiserie', 'conflate', 'conflated', 'conflict', 'conflicted', 'conflicting', 'conflicts', 'confonds', 'conform', 'conformable', 'conformation', 'conforms', 'confortable', 'confound', 'confront', 'confrontation', 'confronted', 'confronting', 'confronts', 'confucanism', 'confucian', 'confuse', 'confused', 'confused/uncomfortable', 'confuses', 'confusing', 'confusion', 'confusions', 'conférence', 'conga…', 'congeniality', 'congjo', 'conglomerate', 'conglomerates', 'congrats', 'congrats🎉', 'congratulate', 'congratulated', 'congratulates', 'congratulating', 'congratulations', 'congressman/member', 'congruent', 'conjecture', 'conjugated', 'conjugation', 'conjure', 'conjuring', 'conked', 'conman', 'conmforting', 'connais', 'connaître', 'connect', 'connected', 'connecting', 'connection', 'connection/love', 'connection/prior', 'connections', 'connections…', 'connectivity', 'connects', 'conned', 'conning', 'connive', 'conniving', 'connoisseur', 'connoisseurs', 'connor', 'connotation', 'connotations', 'conquer', 'conquers', 'cons', 'conscience', 'conscientious', 'consciouly', 'conscious', 'consciously', 'consciousness', 'conscription', 'consecutive', 'consecutively', 'conseguiu', 'consensual', 'consensus', 'consent', 'consequence', 'consequences', 'consequential', 'conservatism', 'conservative', 'conservatives', 'conservatoire', 'conservatory', 'consider', 'considerable', 'considerably', 'considerate', 'consideration', 'considerations', 'considered', 'considering', 'considers', 'consigliere', 'consist', 'consisted', 'consistency', 'consistent', 'consistently', 'consists', 'consolance', 'consolation', 'console', 'consoled', 'consoles', 'consolidation', 'consoling', 'consonants', 'consort', 'conspicuous', 'conspiracy', 'conspiratorial', 'conspire', 'conspired', 'conspires', 'conspiring', 'constance', 'constant', 'constantly', 'constellation', 'constellations', 'constitute', 'constitutes', 'constitution', 'constrained', 'constraints', 'constricting', 'construct', 'constructed', 'construction', 'constructs', 'consulate', 'consultants', 'consultation', 'consulted', 'consume', 'consumed', 'consumer', 'consumers', 'consumes', 'consuming', 'consummate', 'consumption', 'cont', 'contact', 'contact/pda', 'contacted', 'contacting', 'contacts', 'contain', 'contained', 'containing', 'contains', 'contempla', 'contemplate', 'contemplated', 'contemplates', 'contemplating', 'contemplative', 'contemporary', 'contempt', 'contend', 'contended', 'contender', 'contenders', 'content', 'contented', 'contention', 'contentious', 'contents', 'contest', 'context', 'context=3', 'contexts', 'conti', 'contid=2016053001675', 'continent', 'continental', 'contingencies', 'contingency', 'contingent', 'continua', 'continuait', 'continually', 'continuareee⁉️io', 'continuation', 'continue', 'continue.in', 'continued', 'continues', 'continue…', 'continuing', 'continuity', 'continuity/blooper', 'continuity/wardrobe', 'continuous', 'continuously', 'contoured', 'contouring', 'contraat', 'contraband', 'contract', 'contracts', 'contractual', 'contradiction', 'contradictions', 'contradictory', 'contraption', 'contrapuntal', 'contrarian', 'contrary', 'contrast', 'contraste', 'contrasted', 'contrasting', 'contrasts', 'contraty', 'contribute', 'contributed', 'contributes', 'contributing', 'contribution', 'contributions', 'contrivance', 'contrivances', 'contrived', 'control', 'controllare', 'controlled', 'controlling', 'controls', 'controversial', 'controversies', 'controversy', 'conundrum', 'convenience', 'conveniences', 'convenient', 'conveniently', 'convention', 'conventional', 'conventionally', 'conventions', 'conversation', 'conversational', 'conversations', 'conversed', 'conversely', 'conversing', 'conversions', 'convert', 'converted', 'converting', 'convey', 'convey.so', 'conveyed', 'conveying', 'conveys', 'convict', 'convicted', 'conviction', 'convictions', 'convince', 'convinced', 'convinces', 'convincing', 'convincingly', 'convo', 'convoluted', 'convos', 'convoy', 'convulsions', 'cooing', 'cook', 'cooked', 'cooker', 'cookers', 'cookies', 'cooking', 'cooking/fermenting', 'cookout', 'cooks', 'cool', 'coolest', 'cooling', 'coolissue', 'coollssue', 'coolly', 'coolness', 'coop', 'cooper', 'cooperate', 'cooperation', 'coopted', 'coordinate', 'coordinated', 'coordinating', 'coordination', 'coordinator', 'cop', 'cop-out', 'cop/old', 'cope', 'coped', 'copenhagen', 'copied', 'copies', 'coping', 'copious', 'copped', 'copper', 'cops', 'copy', 'copy-cat', 'copycat', 'copying', 'copyright', 'coral', 'cord', 'cordial', 'cordless', 'core', 'coreano', 'corn', 'corndog', 'cornelia', 'corner', 'cornered', 'corners', 'cornerstone', 'cornerstones', 'corniest', 'corny', 'corona-semi-isolation', 'coronation', 'coronavirus', 'corp', 'corpo-commercialised', 'corporal', 'corporate', 'corporate-shark', 'corporate/military', 'corporation', 'corporations', 'correct', 'correct/real', 'corrected', 'correcting', 'correction', 'correctly', 'corrects', 'correlate', 'correlates', 'correlation', 'correspond', 'corresponding', 'corridor', 'corroborate', 'corroborating', 'corrupt', 'corrupted', 'corrupting', 'corruption', 'corruptive', 'coréen', 'cos', 'cosi', 'cosmetic', 'cosmetically', 'cosmetics', 'cosmic', 'cosmo', 'cosmopolitan', 'cost', 'cost-effective', 'costante', 'costar', 'costarring', 'costars', 'costaud', 'costco', 'costed', 'costello', 'costly', 'costs', 'costume', 'costumes', 'costumes…', 'costuming', 'cosy']

### F. Create vector with the frequency

I count how many times each vocabulary word appears in each thread to create a frequency vector for each thread.

In [78]:
vectors = []
for words in thread_words:
    vector = []
    for word in vocab:
        vector.append(words.count(word))
    vectors.append(vector)

It has been 20 minutes and the code is still running, let's check the size of data.

In [77]:
print("number of threads:", len(thread_words))
print("number of vvocabs:", len(vocab))
print("number of words in the first thread:", len(thread_words[0]))

number of threads: 3075
number of vvocabs: 36445
number of words in the first thread: 8

It turns out that the code above ran for 100 minutes. Now let's express the frequency vector with a df.

In [79]:
import pandas as pd

df = pd.DataFrame(vectors, columns=vocab)

df.head()

,'-i,'-sshi,'d,'ll,'m,'re,'s,'ve,'🫠,0,...,🫰🫰🫰🫰,🫶,🫶🍱,🫶🏻,🫶🏻😂😂,🫶🏻🫶🏻🫶🏻,🫶🏻🫶🏻🫶🏻🫶🏻🫶🏻,🫶🏼,🫶🏽,🫶🏽✨
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,1,2,7,0,6,3,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,1,0,1,2,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,2,1,3,1,4,1,0,0,...,0,0,0,0,0,0,0,0,0,0

I am revisiting this parat after Wednesday Lab. After seeing the sample codes on the lab notebook, I think there is a more efficient approach (waiting 100 mins is terrible). Furthermore, my current vector seems to split "I'm" into `I` and `'m`, but the professor's code combines them into `im`, which makes more sense. I will retry following the lab notebook logic. 

I will keep the previous part A, B, and C.

### D2. Remove the punctuation, lowercase, and tokenize each thread

In [84]:
import string
import pandas as pd

I used logic similar to the lab notebook.

In [91]:
thread_words = []
for thread in threads:
    sentence = get_thread_sentence(thread)
    sentence_noPunct = "".join([ch for ch in sentence if not ch in string.punctuation])
    words = sentence_noPunct.lower().split()
    thread_words.append(words)

### E2. Create vocabulary for unique terms

I used vocab.append() and got an error, I learned about `vocab.update()`.

In [96]:
vocab = set()
for words in thread_words:
    vocab.update(words)

vocab = sorted(vocab)

print("Number of threads:", len(thread_words))
print("Vocabulary size:", len(vocab))
print(vocab[:20])

Number of threads: 3075
Vocabulary size: 39333
['0', '00000001', '00001', '0001', '0010', '0011', '0030', '0038', '007', '01', '014', '0140', '017', '01823', '01httpswwwgentlemonstercomshopver1detailphpitid1572394578', '01x16', '02', '020', '0200', '02021988']

### F2. Create a frequency vector for every thread

In [97]:
vectors = []
for words in thread_words:
    vector = []
    for word in vocab:
        vector.append(words.count(word))
    vectors.append(vector)

Yay! It only took less than 5 minutes this time.

### G2. Display Frequency vector on a df

In [98]:
df = pd.DataFrame(vectors, columns=vocab)
df.head()

,0,00000001,00001,0001,0010,0011,0030,0038,007,01,...,🫰🫰🫰🫰,🫶,🫶🍱,🫶🏻,🫶🏻😂😂,🫶🏻🫶🏻🫶🏻,🫶🏻🫶🏻🫶🏻🫶🏻🫶🏻,🫶🏼,🫶🏽,🫶🏽✨
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

## 2. Calculate the similarity score between every two threads, and save the dataframe into a CSV file.

### A. Define cosine similarity function

I copied the code from the lecture notes. I originally used a nested for loops and it was taking forever. This function is much more efficient.

In [105]:
import numpy as np
from numpy.linalg import norm

def cosineSimilarity(vec1, vec2):
    """Calculate the cosine similarity between two vectors."""
    V1 = np.array(vec1)
    V2 = np.array(vec2)
    cosine = np.dot(V1, V2) / (norm(V1) * norm(V2))
    return cosine

### B. Calculate the Cosine Similarity

I will run a for loop to call the cosine similarity formula.

In [ ]:
similarities = []

for i in range(len(vectors)):
    row = []

    for j in range(len(vectors)):
        similarity = cosineSimilarity(vectors[i], vectors[j])
        row.append(similarity)

    similarities.append(row)

The code above ran for 600 minutes and is still not done yet. I need to look for another more efficient approach. I googled about `scikit-learn`. It is much more efficient and only took 2 steps.

In [114]:
from sklearn.metrics.pairwise import cosine_similarity

In [115]:
similarities = cosine_similarity(vectors)
similarities_df = pd.DataFrame(similarities)
similarities_df.head(20)

,0,1,2,3,4,5,6,7,8,9,...,3065,3066,3067,3068,3069,3070,3071,3072,3073,3074
0,1.000000,0.057374,0.030890,0.010004,0.061422,0.024456,0.017851,0.068425,0.092685,0.039528,...,0.060059,0.073213,0.125000,0.135565,0.125868,0.017157,0.059827,0.015988,0.083853,0.044544
1,0.057374,1.000000,0.525775,0.806039,0.795403,0.637483,0.796317,0.871319,0.635587,0.449042,...,0.821379,0.496221,0.043030,0.537850,0.690618,0.797749,0.809850,0.584933,0.408394,0.205302
2,0.030890,0.525775,1.000000,0.496912,0.453334,0.362612,0.412472,0.503718,0.373013,0.195366,...,0.549151,0.445077,0.061780,0.435512,0.491454,0.481918,0.551798,0.414858,0.193403,0.154107
3,0.010004,0.806039,0.496912,1.000000,0.678696,0.542157,0.702914,0.770414,0.590241,0.411261,...,0.746915,0.430081,0.040016,0.464558,0.605417,0.724527,0.756828,0.546377,0.355677,0.203200
4,0.061422,0.795403,0.453334,0.678696,1.000000,0.555183,0.652910,0.806582,0.590757,0.440261,...,0.815206,0.525238,0.053232,0.570451,0.621783,0.749548,0.792723,0.476086,0.489858,0.253896
5,0.024456,0.637483,0.362612,0.542157,0.555183,1.000000,0.543095,0.629899,0.453336,0.286143,...,0.551503,0.386746,0.048912,0.436421,0.487589,0.538179,0.552023,0.347213,0.328109,0.104577
6,0.017851,0.796317,0.412472,0.702914,0.652910,0.543095,1.000000,0.757322,0.586186,0.341530,...,0.676478,0.406728,0.044629,0.439126,0.568923,0.691353,0.731755,0.504611,0.317341,0.178117
7,0.068425,0.871319,0.503718,0.770414,0.806582,0.629899,0.757322,1.000000,0.620272,0.407704,...,0.812961,0.513830,0.046817,0.564907,0.667246,0.785593,0.817625,0.534331,0.421966,0.218165
8,0.092685,0.635587,0.373013,0.590241,0.590757,0.453336,0.586186,0.620272,1.000000,0.213541,...,0.564127,0.330370,0.013241,0.366827,0.458643,0.560946,0.604899,0.365809,0.325678,0.141549
9,0.039528,0.449042,0.195366,0.411261,0.440261,0.286143,0.341530,0.407704,0.213541,1.000000,...,0.525595,0.296347,0.079057,0.358544,0.378129,0.383394,0.420491,0.369082,0.274004,0.154945
10,0.117851,0.333569,0.145617,0.264092,0.193030,0.345857,0.370271,0.258047,0.162285,0.149071,...,0.209265,0.096637,0.117851,0.116193,0.166138,0.210280,0.227442,0.256256,0.158114,0.041996
11,0.104973,0.787464,0.428026,0.633239,0.685167,0.562215,0.635258,0.739825,0.550405,0.369298,...,0.687887,0.384271,0.078730,0.451499,0.601180,0.637545,0.664895,0.426296,0.311012,0.177683
12,0.079057,0.246444,0.136756,0.183486,0.271926,0.139205,0.146773,0.202713,0.125612,0.225000,...,0.276629,0.222260,0.079057,0.241628,0.206976,0.188080,0.211161,0.262908,0.176777,0.169031
13,0.146618,0.690718,0.483098,0.582795,0.568883,0.481275,0.610713,0.621418,0.486624,0.303946,...,0.622616,0.381668,0.065164,0.419209,0.621713,0.578370,0.628296,0.489669,0.273206,0.179962
14,0.514496,0.232868,0.127143,0.178430,0.224720,0.083883,0.171444,0.202580,0.154412,0.216930,...,0.259742,0.160717,0.000000,0.219811,0.276304,0.180463,0.213149,0.175485,0.115045,0.030557
15,0.116248,0.561353,0.253757,0.482233,0.485529,0.413172,0.475910,0.528609,0.371460,0.379861,...,0.530614,0.351783,0.000000,0.404962,0.440908,0.482205,0.513308,0.361806,0.355248,0.144986
16,0.044662,0.766730,0.452512,0.673175,0.562785,0.579616,0.689912,0.699125,0.539314,0.277759,...,0.588720,0.352272,0.029775,0.393365,0.589135,0.625937,0.640360,0.470330,0.306259,0.111406
17,0.168613,0.617374,0.424255,0.550819,0.541301,0.428852,0.517719,0.544520,0.508211,0.319921,...,0.593679,0.362711,0.076642,0.418624,0.589616,0.515450,0.564673,0.474466,0.277632,0.136557
18,0.041767,0.842944,0.474794,0.721552,0.754872,0.587191,0.740922,0.802457,0.581470,0.458507,...,0.765708,0.492066,0.047734,0.525335,0.612839,0.729690,0.775582,0.602917,0.422945,0.223256
19,0.053477,0.843026,0.478390,0.737418,0.693540,0.600549,0.731252,0.773890,0.594210,0.388949,...,0.743122,0.456670,0.064172,0.507206,0.625716,0.718813,0.743739,0.560195,0.382648,0.247732

It only took 1.4s to calculate all the cosine similarities.

### C. Save the df into a csv file

This is a straightforward step!

In [117]:
similarities_df.to_csv("CosSimilarity.csv",index = True)

I could not push the csv file to github, because it is larger than 100 MB.

## 3. Given one thread ID, gives top 5 most similar threads

In [ ]:
print(threads[1]["post_id"])
#print(threads[1])

ffh52z
{'post_id': 'ffh52z', 'timestamp': 1583693959, 'author': 'bruisedlee123', 'subreddit': 'CrashLandingOnYou', 'title': 'ok, let’s get this started! What are your thoughts about the show?', 'selftext': 'I haven’t seen a kdrama for the longest time and it was actually my dad who chose to stream CLOY on Netflix. He stopped watching after the second episode but I went on after immediately falling in love with the leads. Hyun Bin is just so charismatic as Capt. Ri Jeong Hyeok and Son Ye-jin is perfect as Yoon Se-ri. She’s definitely got the rom-com and drama genre down pat! I also loved Capt. Ri’s squad, most especially Pyo Chi Su ☺️ (we can probably talk about individual characters next time).\n\nCLOY tackled politics, drama and deception, family issues, friendships - and best of all, pure unconditional love, love brought about by fate - all in one highly entertaining and well-written package. \n\nI’m planning on doing a rewatch soon, when I get a chance!', 'url': 'https://www.reddit.com/r/CrashLandingOnYou/comments/ffh52z/ok_lets_get_this_started_what_are_your_thoughts/', 'score': 28, 'permalink': 'https://reddit.com/r/CrashLandingOnYou/comments/ffh52z/ok_lets_get_this_started_what_are_your_thoughts/', 'comments': [{'comment_id': 'fk0rooq', 'parent_id': 't3_ffh52z', 'author': 'chimichangarolls', 'comment_body': "i'm so emotionally drained and exhausted from being in awe of this show even though i finished watching 2 weeks ago. my brain doesn't work cuz i'm thinking about CLOY and my favorite part of it other than the couple is that the women have really 3D roles... like Seri can cry nonstop but you still know she a boss.", 'score': 19, 'created_utc': 1583764623, 'replies': [{'comment_id': 'fk1c27d', 'parent_id': 't1_fk0rooq', 'author': 'bruisedlee123', 'comment_body': 'Did you have a favorite episode? Mine would have to be ep. 9 ☺️', 'score': 2, 'created_utc': 1583776621, 'replies': [{'comment_id': 'fsfm0lq', 'parent_id': 't1_fk1c27d', 'author': 'tmstms', 'comment_body': "I have not finished it yet, but I already see your point. Episode 9 is when you feel things are going to end happily. Also the stuff in RJH;s parents' home is priceless.", 'score': 2, 'created_utc': 1590941768}]}]}, {'comment_id': 'fk5qnci', 'parent_id': 't3_ffh52z', 'author': 'FunKyChick217', 'comment_body': 'I love this show. I stumbled across it on Netflix, gave it a try, and fell in love. I finished it this morning and already miss it. I love Yoon Se-Ri and Jeong Hyeok and nearly all of the other characters. I was so happy with the ending. I’ve added two more kdramas to my Netflix list.', 'score': 13, 'created_utc': 1583885982, 'replies': [{'comment_id': 'fkwjjk7', 'parent_id': 't1_fk5qnci', 'author': 'amandas430', 'comment_body': 'Which ones!', 'score': 1, 'created_utc': 1584594446, 'replies': [{'comment_id': 'fky68ki', 'parent_id': 't1_fkwjjk7', 'author': 'FunKyChick217', 'comment_body': 'Itaewon Class, Chocolate, When the Camellia Blooms', 'score': 4, 'created_utc': 1584642396, 'replies': [{'comment_id': 'fky7xtf', 'parent_id': 't1_fky68ki', 'author': 'amandas430', 'comment_body': 'Thank you :)', 'score': 1, 'created_utc': 1584643414}]}]}]}, {'comment_id': 'fk7icpl', 'parent_id': 't3_ffh52z', 'author': 'hawkgirl2301', 'comment_body': "I'm currently obsessed with Hyun Bin. I've never watched Korean dramas, the most asian movie I ever got to watch was the one by Daniel Henney! And this show comes on Netflix and I'm awed. I've literally added so many K dramas to my list now!\n\nThis is a well rounded drama- irrespective of language or Korean drama wise. It had all characters play a role and there's comic angle for some characters which is just so much fun to watch! They really did a great job with this one. ❤️", 'score': 7, 'created_utc': 1583937061, 'replies': [{'comment_id': 'fk7u6bo', 'parent_id': 't1_fk7icpl', 'author': 'bruisedlee123', 'comment_body': 'Good on ya, girl! And yes I agree, it’s hard not to fall in love with Hyun Bin. You should probably check him out in Secret Garden too. \n\nThe writing on this show, to me, is practically flawless. And the ending was definitely satisfying.', 'score': 7, 'created_utc': 1583943693, 'replies': [{'comment_id': 'fk7ubs6', 'parent_id': 't1_fk7u6bo', 'author': 'hawkgirl2301', 'comment_body': "I've already started My lovely Sam Soon. Secret garden is next ❤️ thanks for the recommendation 🥰", 'score': 3, 'created_utc': 1583943773, 'replies': [{'comment_id': 'fk7ufcr', 'parent_id': 't1_fk7ubs6', 'author': 'bruisedlee123', 'comment_body': 'You’re welcome! 😊', 'score': 1, 'created_utc': 1583943826}]}]}]}, {'comment_id': 'fkan99x', 'parent_id': 't3_ffh52z', 'author': 'mikasa-london', 'comment_body': 'Alright so, a week ago my partner went back to his family home for holiday, we recently moved in a big house and I was terrified being alone in there, super anxious. The first night was awful as I was stressing the sh*t out of me anytime I would hear a sound.. Even the wind was an enemy. So I went lurking on Netflix about to watch a good old How I Met Your Mother episode trying to ease my pain when I stumble into CLOY.. I never watched a Korean Drama but the storyline seemed interesting and I really needed something to keep me occupy so I played it....\n\nOh my lord\n\nDid I even sleep more than 5hours per night that week ? I’m not sure. Did I call my mother once ? I’m not sure. I got literally sucked by the show. I would watch it in the morning while drinking my coffee, then in the tube on my way to work, then on my break, then in the tube again and straight on tv with my dinner at home. At work I couldn’t stay focus at time being too busy wondering what’s gonna happen next and If I was talking to my colleague it would only be to spread a strong and passionate propaganda about the show.. I started texting my partner less, actually I started texting everyone less lol. \n\nI still not fully comprehend how a show could make me cry in a crowded tube to then make me laugh a minute later making me look like an absolute lunatic. \n\nEverything was perfect, rarely did I watch a show where the side characters were as charismatic and as important for me as the main ones. \n\nWhen you think that each episode was around 1h20 in length which round it up to 35hours or so in total. You wonder... HOW DID THEY MANAGE TO MAKE EVERY DAMN SECONDS SO SPECIAL???? I’m still in awe... \n\nI was so grateful for the show to tickle my favourite subjects with such delicacy; Romance, History and Comic. Surely in general I can find Romance and History genre or Romance and Comic genre in a movie or a show but did I ever cry laugh and learn all at the same time? \nBeing able to discover more about Korea’s lifestyle and the sinkhole there is between the South and the North was a blessing. I think as much for us than for the Korean themselves. \nEvery time Seri would mention the reunification as “you can get your gift when we reunify” I’d be thinking BUT THERE IS NO REUNIFICATION SO WHEN WILL THEY SEE EACHOTHER AGAIN ? HOW IS HE GONNA MEET IS FAVOURITE KDRAMA ACTRESS ? WHAT WILL THE CREATOR DO TO MAKE THEM MEET AGAIN WHILE STILL BEING ACCURATE WITH THE PRESENT POLITICS???? \n\nThey figured a way and they smashed it. \n\n\nThe day my partner came back so 6 days later, I was watching the last episode. By the time he arrived I had 1minute and 20secondes left. I already saw the beautiful last scene where our lover find eachother again and I was pretty proud of myself for managing it so well.. not event crying! Then, after being reunited with my own lover I tell him “ hey I have one minute left on my show do you mind if I watch?” And he was like “yeah sure” \n\nI put the show back on and really the last minute was literally just the end credits. However that’s when I understood it was over like really over.. I froze for a second and bursted into tears, threw myself in my partners arms, yelling nonsense... I wonder if he thought it was because I missed him haha. After that I told him I was in a mourning period and out of respect for the show, begged him to not propose me to watch anything else for the coming week... \n\nThat’s how much I liked it. \n\nNow my goal is to spread the love for CLOY to the people around me hoping they will give it a chance so they can become lunatics with me :)', 'score': 18, 'created_utc': 1584014192}, {'comment_id': 'fkfuewy', 'parent_id': 't3_ffh52z', 'author': 'snoreweezy', 'comment_body': "it's my first Kdrama. I'm telling everyone to watch it. It's so well-written, production value is high, and all the characters are given a moment to shine so there's amazing character development arc. Also, I now have a huge crush on HB.", 'score': 11, 'created_utc': 1584142781}, {'comment_id': 'fkj9ps1', 'parent_id': 't3_ffh52z', 'author': 'Myfamily2', 'comment_body': 'I cried a lot. Period', 'score': 8, 'created_utc': 1584239896}, {'comment_id': 'fkmn336', 'parent_id': 't3_ffh52z', 'author': 'vv155', 'comment_body': 'I absolutely adore CLOY. This was my first time watching a kdrama but it was an amazing first experience. (I’m watching Something In The Rain now with the same female lead.) I fell in love with all the characters in CLOY and the emotional development of the characters was so fulfilling to see. I usually don’t like endings of shows like this because I always feel like I want to see more but I was very satisfied with how they wrapped up the series. Overall, a great watch, super well written, phenomenal acting and casting. I will definitely recommend it to everyone I know!', 'score': 6, 'created_utc': 1584333394}, {'comment_id': 'fl6jhxd', 'parent_id': 't3_ffh52z', 'author': 'EatThatIcecream', 'comment_body': 'Anyone notice that  Park Kwang-beom had a noticeably less amount of lines in the show later on?', 'score': 1, 'created_utc': 1584871769, 'replies': [{'comment_id': 'fl7oorp', 'parent_id': 't1_fl6jhxd', 'author': 'bruisedlee123', 'comment_body': 'I’d like to think maybe because his character was the handsome yet shy type, the one who doesn’t even realize how good-looking he is and is so humble about it...especially when they got to Seoul. When they were back in NoKor and was Capt. Ri’s sort of right hand he had more exposure and dialogue...', 'score': 6, 'created_utc': 1584906131, 'replies': [{'comment_id': 'fl7zy0j', 'parent_id': 't1_fl7oorp', 'author': 'EatThatIcecream', 'comment_body': 'Interesting take!', 'score': 4, 'created_utc': 1584912971, 'replies': [{'comment_id': 'fl9v7im', 'parent_id': 't1_fl7zy0j', 'author': 'bruisedlee123', 'comment_body': 'thanks! I wouldn’t want to think the writers just got lazy 😆', 'score': 3, 'created_utc': 1584970157}]}]}, {'comment_id': 'flpebsq', 'parent_id': 't1_fl6jhxd', 'author': 'thedoobalooba', 'comment_body': 'I thought his character was the strong, silent type. He was always calmer and quieter than the rest of the group.', 'score': 3, 'created_utc': 1585357493}]}, {'comment_id': 'fme7duc', 'parent_id': 't3_ffh52z', 'author': 'pela_ka', 'comment_body': 'cloy the first kdrama i watched and i love it!!', 'score': 2, 'created_utc': 1585992515}, {'comment_id': 'fn9jb48', 'parent_id': 't3_ffh52z', 'author': 'admiral_derpness', 'comment_body': 'my wife kept asking me to watch kdrama and i\'m like "i don\'t want romance, just action or sci-fi." so past months they kept watching em and i\'d be on programming or some hobby thing until this lockdown. ok fine, i\'ll try em.  watched a fight one and that was awesome, so tried this and i just cry or weep - i\'m a mess. my\nkids laugh cause i barely cry elsewise but this show wrecked me. now it\'s all i wanna watch. i\'ll be sad when it\'s over, and Ri is like a role model now - how to be that awesome superhero man.', 'score': 3, 'created_utc': 1586775181}]}

### A. Search for the index of the thread given its ID

I will use the `threads[1]` as an example for this question.

In [225]:
def get_id_thread(id):
   for i in range(len(threads)):
      if threads[i]["post_id"] == id:
         return i


id_index = get_id_thread("ffh52z")

### B. Find the top 5 most similar threads

Gives indices from smallest to largest, then reverse those resulting indices.

In [226]:
print(id_index)
np.argsort(similarities[id_index])[::-1]

1

array([   1,  452,  574, ..., 2855, 2872, 1776], shape=(3075,))

We want to exclude the first one, since it is the thread itself. The thread's cosine similarity with itself is 1.

In [227]:
five_similar = np.argsort(similarities[id_index])[::-1][1:6]
five_similar

array([ 452,  574, 2201, 2332,  387])

### C. Print the 5 most similar threads' ID and subject title

In [228]:
#threads[i]
i = 0
for ind in five_similar :
    i=1+i
    print("Top " +str(i)+ " most similar thread's ID: "+threads[ind]['post_id'] +" ; Subject title: " + threads[ind]['title'] )

Top 1 most similar thread's ID: i42ez5 ; Subject title: How come you started watching it?
Top 2 most similar thread's ID: iy5qeu ; Subject title: Withdrawal, anyone?
Top 3 most similar thread's ID: 17tpx8l ; Subject title: I just finished “Crash Landing On You” and I will never be the same.
Top 4 most similar thread's ID: 1ci4cmh ; Subject title: I have just finished binge-watching Crash Landing On You. I am overwhelmed.
Top 5 most similar thread's ID: hp9elr ; Subject title: post-series depression

### D. Combine A, B, and C into one function

In [230]:
def find_similarities (id):

    # A. find i
    for i in range(len(threads)):
        if threads[i]["post_id"] == id:
            id_ind = i
            print(id_ind)

    # B. find five_similar
    five_similar = np.argsort(similarities[id_ind])[::-1][1:6]
    print(id_ind)
    print(five_similar)

    # C. print them
    j = 0
    for ind in five_similar :
        j+=1
        print("Top " +str(j)+ " most similar thread's ID: "+threads[ind]['post_id'] +" ; Subject title: " + threads[ind]['title'] )

In [231]:
find_similarities("ffh52z")

1
1
[ 452  574 2201 2332  387]
Top 1 most similar thread's ID: i42ez5 ; Subject title: How come you started watching it?
Top 2 most similar thread's ID: iy5qeu ; Subject title: Withdrawal, anyone?
Top 3 most similar thread's ID: 17tpx8l ; Subject title: I just finished “Crash Landing On You” and I will never be the same.
Top 4 most similar thread's ID: 1ci4cmh ; Subject title: I have just finished binge-watching Crash Landing On You. I am overwhelmed.
Top 5 most similar thread's ID: hp9elr ; Subject title: post-series depression

Yay! The answers are consistent with section A, B, and C.

## 4. Verification

##### I used the thread explorer to examine the five most similar threads to `ffh52z`. The original thread is mainly a general discussion of viewers’ experiences with CLOY, including their love for the characters and story, emotional reactions, and overall appreciation of the show. The five most similar threads seemed reasonable because they discussed many of the same themes, such as discovering CLOY, becoming emotionally attached to the show, loving the characters, rewatching it, and struggling to move on after finishing it. Although each thread focused on a slightly different topic, they reflected many of the main themes discussed in the original thread.

#### However, since all of the threads come from the same CLOY subreddit, I am not fully convinced by only looking at the five most similar threads. Many threads may naturally use similar words and discuss similar topics because they are all about the same show. To further check how well the cosine similarity works, I also want to look at the **least similar thread to `ffh52z`** and compare its content with the original thread. If the least similar thread discusses noticeably different topics, this would give me more confidence that the similarity measure is actually distinguishing between different discussions.

In [234]:
least_similar = np.argsort(similarities[id_index])[0]
least_similar
print(threads[least_similar]["post_id"])
print(threads[least_similar]["title"])

ttn4es
Login • Instagram

#### This thread is deleted, so let me look for more.

In [236]:
least_similars = np.argsort(similarities[id_index])[0:5]
least_similars
j = 0
for ind in least_similars :
    j+=1
    print("Top " +str(j)+ " least similar thread's ID: "+threads[ind]['post_id'] +" ; Subject title: " + threads[ind]['title'] )

Top 1 least similar thread's ID: ttn4es ; Subject title: Login • Instagram
Top 2 least similar thread's ID: 1nilhlv ; Subject title: Speechless
Top 3 least similar thread's ID: 1n4jfwo ; Subject title: RJH 💔 YSR
Top 4 least similar thread's ID: h7g9hv ; Subject title: CCG’s military position?
Top 5 least similar thread's ID: kz14r2 ; Subject title: Fanfics!!

#### They are all deleted, so let me look for even more threads.

In [245]:
least_similarss = np.argsort(similarities[id_index])[30:40]
least_similarss
j = 0
for ind in least_similarss :
    j+=1
    print("Top " +str(j)+ " least similar thread's ID: "+threads[ind]['post_id'] +" ; Subject title: " + threads[ind]['title'] )

Top 1 least similar thread's ID: 1hyrxyi ; Subject title: Son Ye-jin's Birthday Instagram Post
Top 2 least similar thread's ID: mi0htz ; Subject title: It’s finally happening??
Top 3 least similar thread's ID: k2gyk0 ; Subject title: Lady...[Spoilers, Ep 13]
Top 4 least similar thread's ID: jlroby ; Subject title: Happy Halloween!!!! Uwu
Top 5 least similar thread's ID: 1qx3zat ; Subject title: BTS from sets
Top 6 least similar thread's ID: jbwzwf ; Subject title: Man Bok
Top 7 least similar thread's ID: 1ko78xu ; Subject title: Absolutely stunning frames
Top 8 least similar thread's ID: jpode3 ; Subject title: Dangerous Landings Great Pilots
Top 9 least similar thread's ID: 1lfucj3 ; Subject title: Park Su-Chan
Top 10 least similar thread's ID: 19dlwh0 ; Subject title: Pyo Chi-su?!?!

#### I initially compared `ffh52z` with its least similar threads and found that they were mostly deleted or contained very few words. This result makes sense because threads with very little text have fewer words that can overlap with ffh52z, resulting in low cosine similarity. This gives me some confidence that the cosine similarity calculation is behaving as expected. 

#### However, I also want to test whether it can distinguish between threads that contain substantial amounts of text. Therefore, I will examine some threads that rank lower than the top five but still contain enough content, and compare their topics with ffh52z.

In [248]:
len(similarities)

less_similars = np.argsort(similarities[id_index])[::-1][400:406]
j = 0
for ind in less_similars :
    j+=1
    print("Thread's ID: "+threads[ind]['post_id'] +" ; Subject title: " + threads[ind]['title'] )

Thread's ID: 1ri1aqc ; Subject title: 2026 CLOY (re)watch Ep. 3 Discussion
Thread's ID: lfmyh6 ; Subject title: DVD / Blu-Ray Boxset?
Thread's ID: koy4kt ; Subject title: OST - Flower made me teary!
Thread's ID: 1rcamj7 ; Subject title: Character Question: The soldiers and the Tin Man, the Scarecrow, and the Cowardly Lion
Thread's ID: 1n093pc ; Subject title: Favorite CLOY Episode
Thread's ID: lfdhrf ; Subject title: Biggest Tearjerker?

#### To further test the similarity results, I looked at several threads ranked around 400th most similar to ffh52z. Unlike the top five, which shared many of the original thread’s main themes, these threads tended to focus on one narrower topic, such as a specific episode, the OST, favorite emotional scenes, or buying a DVD/Blu-ray. They still had some overlap with ffh52z, which makes sense because they are all discussions about CLOY, but the overlap was much more limited. This comparison gives me more confidence that the cosine similarity is meaningfully distinguishing between discussions within the same subreddit, rather than simply identifying that they are all about the same show.

## 5. Investigate Stop Words

### A. Remove the stop words

I googled for the stop word list and the library it is at. I defined the stop words.

In [254]:
import nltk
from textblob import TextBlob
from nltk.corpus import stopwords

nltk.download('stopwords')
stop_words = set(stopwords.words('english'))

[nltk_data] Downloading package stopwords to
[nltk_data]     /Users/lejunli/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

I want to first define a function that removes stop words.

In [256]:
def remove_stopwords(words):
    # create an empty list
    wordlist= []
    for word in words:
        if word.lower() not in stop_words:
            wordlist.append(word)
    return wordlist

I want to remove stopwords for all threads

In [257]:
filtered_thread_words = []

for words in thread_words:
    removed_stopwords = remove_stopwords(words)
    filtered_thread_words.append(removed_stopwords)

Let's do a sanity check!'

In [260]:
print(len(thread_words[1]))
print(len(filtered_thread_words[1]))
print(thread_words[1][:50])
print(filtered_thread_words[1][:50])

1535
794
['ok', 'let’s', 'get', 'this', 'started', 'what', 'are', 'your', 'thoughts', 'about', 'the', 'show', 'i', 'haven’t', 'seen', 'a', 'kdrama', 'for', 'the', 'longest', 'time', 'and', 'it', 'was', 'actually', 'my', 'dad', 'who', 'chose', 'to', 'stream', 'cloy', 'on', 'netflix', 'he', 'stopped', 'watching', 'after', 'the', 'second', 'episode', 'but', 'i', 'went', 'on', 'after', 'immediately', 'falling', 'in', 'love']
['ok', 'let’s', 'get', 'started', 'thoughts', 'show', 'haven’t', 'seen', 'kdrama', 'longest', 'time', 'actually', 'dad', 'chose', 'stream', 'cloy', 'netflix', 'stopped', 'watching', 'second', 'episode', 'went', 'immediately', 'falling', 'love', 'leads', 'hyun', 'bin', 'charismatic', 'capt', 'ri', 'jeong', 'hyeok', 'son', 'yejin', 'perfect', 'yoon', 'seri', 'she’s', 'definitely', 'got', 'romcom', 'drama', 'genre', 'pat', 'also', 'loved', 'capt', 'ri’s', 'squad']

In [268]:
filtered_vocab = set()
for words in filtered_thread_words:
    for word in words:
        filtered_vocab.add(word)

filtered_vocab = sorted(list(filtered_vocab))

Now-- Create the vector, same as the previous part!

Update: I tried using the code from F2 section, but it is inefficient as it takes more than 4 minutes to load. I looked up for a faster way using Counter.

In [279]:
from collections import Counter

filtered_vectors = []

for words in filtered_thread_words:
    counts = Counter(words)
    filtered_vector = []

    for word in filtered_vocab:
        filtered_vector.append(counts[word])

    filtered_vectors.append(filtered_vector)

Finally, display the vectors on a df

In [280]:
df = pd.DataFrame(filtered_vectors, columns=filtered_vocab)
df.head()

,0,00000001,00001,0001,0010,0011,0030,0038,007,01,...,🫰🫰🫰🫰,🫶,🫶🍱,🫶🏻,🫶🏻😂😂,🫶🏻🫶🏻🫶🏻,🫶🏻🫶🏻🫶🏻🫶🏻🫶🏻,🫶🏼,🫶🏽,🫶🏽✨
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

### B. Recalculate the cosine similarity

In [281]:
filtered_similarities = cosine_similarity(filtered_vectors)
filtered_similarities_df = pd.DataFrame(filtered_similarities)
filtered_similarities_df.head(20)

,0,1,2,3,4,5,6,7,8,9,...,3065,3066,3067,3068,3069,3070,3071,3072,3073,3074
0,1.000000,0.000000,0.000000,0.000000,0.026162,0.000000,0.000000,0.013558,0.000000,0.000000,...,0.000000,0.000000,0.188982,0.063246,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
1,0.000000,1.000000,0.122788,0.356546,0.423038,0.119753,0.397293,0.472193,0.127897,0.124776,...,0.436439,0.185925,0.039841,0.204000,0.216600,0.366505,0.370293,0.213444,0.125988,0.090142
2,0.000000,0.122788,1.000000,0.186653,0.076189,0.035806,0.030039,0.146654,0.036980,0.048280,...,0.191391,0.104530,0.052414,0.114018,0.122663,0.068730,0.139073,0.033968,0.000000,0.040893
3,0.000000,0.356546,0.186653,1.000000,0.229654,0.052885,0.190144,0.287222,0.089732,0.132433,...,0.336071,0.097045,0.000000,0.111035,0.127418,0.240956,0.285058,0.105120,0.090929,0.094912
4,0.026162,0.423038,0.076189,0.229654,1.000000,0.067551,0.165761,0.369610,0.158718,0.122965,...,0.449203,0.143960,0.000000,0.153882,0.117488,0.383012,0.392810,0.128168,0.215762,0.123437
5,0.000000,0.119753,0.035806,0.052885,0.067551,1.000000,0.006991,0.157532,0.017213,0.022473,...,0.067948,0.068119,0.048795,0.073485,0.061489,0.063984,0.086930,0.021082,0.015430,0.038069
6,0.000000,0.397293,0.030039,0.190144,0.165761,0.006991,1.000000,0.295155,0.140798,0.018854,...,0.215349,0.106130,0.000000,0.102748,0.121593,0.196134,0.197838,0.145912,0.045308,0.047907
7,0.013558,0.472193,0.146654,0.287222,0.369610,0.157532,0.295155,1.000000,0.159082,0.070805,...,0.431648,0.179869,0.051245,0.216088,0.199263,0.374235,0.368286,0.172695,0.100472,0.107948
8,0.000000,0.127897,0.036980,0.089732,0.158718,0.017213,0.140798,0.159082,1.000000,0.034816,...,0.150490,0.045227,0.000000,0.050596,0.027217,0.078791,0.106018,0.059876,0.063746,0.019659
9,0.000000,0.124776,0.048280,0.132433,0.122965,0.022473,0.018854,0.070805,0.034816,1.000000,...,0.140486,0.065608,0.065795,0.088077,0.130289,0.092913,0.114722,0.028427,0.083225,0.102665
10,0.223607,0.056569,0.000000,0.052342,0.058501,0.000000,0.217962,0.000000,0.000000,0.000000,...,0.083691,0.101130,0.169031,0.084853,0.000000,0.051150,0.057664,0.109545,0.053452,0.000000
11,0.000000,0.421725,0.122663,0.211036,0.250996,0.035136,0.165809,0.365316,0.149691,0.059222,...,0.310370,0.112834,0.077152,0.167829,0.162037,0.220495,0.288543,0.133333,0.032530,0.080257
12,0.000000,0.093553,0.000000,0.048692,0.065305,0.035806,0.000000,0.030083,0.018490,0.000000,...,0.032439,0.000000,0.000000,0.000000,0.037743,0.074017,0.063576,0.067937,0.033150,0.081786
13,0.083624,0.345539,0.046386,0.166387,0.201277,0.032388,0.199254,0.240363,0.066899,0.014557,...,0.156492,0.081944,0.000000,0.084622,0.125178,0.197665,0.164134,0.102418,0.069965,0.098638
14,0.333333,0.126491,0.000000,0.019507,0.148253,0.000000,0.108306,0.072310,0.000000,0.000000,...,0.015595,0.000000,0.000000,0.042164,0.022680,0.025416,0.004776,0.027217,0.000000,0.000000
15,0.000000,0.336475,0.056033,0.124141,0.158567,0.104328,0.153168,0.262959,0.074078,0.000000,...,0.185493,0.098986,0.000000,0.102220,0.054986,0.119386,0.150510,0.057735,0.060368,0.044682
16,0.000000,0.370228,0.084813,0.178954,0.178293,0.022559,0.175061,0.239285,0.075721,0.091255,...,0.179853,0.085615,0.000000,0.088413,0.160510,0.133239,0.168984,0.114140,0.104428,0.038646
17,0.078326,0.265853,0.065171,0.174180,0.192623,0.020224,0.144214,0.203896,0.125322,0.054539,...,0.176809,0.106273,0.000000,0.138706,0.133235,0.146321,0.143636,0.102325,0.046809,0.011549
18,0.000000,0.426595,0.067212,0.207999,0.290588,0.093857,0.231845,0.296804,0.096935,0.112495,...,0.305644,0.170491,0.000000,0.163486,0.093438,0.301809,0.236668,0.194570,0.139997,0.035731
19,0.000000,0.494968,0.055656,0.187893,0.283499,0.051813,0.242694,0.276606,0.124861,0.081508,...,0.230794,0.133614,0.025282,0.145952,0.120609,0.276692,0.234787,0.144731,0.099936,0.216973

### C. Use the same thread `ffh52z` and find its new top 5

In [289]:
def find_filtered_similarities (id):

    # A. find i
    for i in range(len(threads)):
        if threads[i]["post_id"] == id:
            id_ind = i
            print(id_ind)

    # B. find five_filtered_similar
    five_filtered_similar = np.argsort(filtered_similarities[id_ind])[::-1][1:6]

    # C. print them
    j = 0
    for ind in five_filtered_similar :
        j+=1
        print("Top " +str(j)+ " most similar thread's ID: "+threads[ind]['post_id'] +" ; Subject title: " + threads[ind]['title'] )

In [290]:
find_filtered_similarities("ffh52z")

1
Top 1 most similar thread's ID: 17tpx8l ; Subject title: I just finished “Crash Landing On You” and I will never be the same.
Top 2 most similar thread's ID: i42ez5 ; Subject title: How come you started watching it?
Top 3 most similar thread's ID: kclv6n ; Subject title: Happy Birthday to CLOY!
Top 4 most similar thread's ID: iy5qeu ; Subject title: Withdrawal, anyone?
Top 5 most similar thread's ID: u1lawc ; Subject title: Just finished the show…

### D.Conclusion -- Comparing with the unfiltered function

Response from earlier section:  
Top 1 most similar thread's ID: i42ez5 ; Subject title: How come you started watching it?  
Top 2 most similar thread's ID: iy5qeu ; Subject title: Withdrawal, anyone?  
Top 3 most similar thread's ID: 17tpx8l ; Subject title: I just finished “Crash Landing On You” and I will never be the same.  
Top 4 most similar thread's ID: 1ci4cmh ; Subject title: I have just finished binge-watching Crash Landing On You. I am overwhelmed.  
Top 5 most similar thread's ID: hp9elr ; Subject title: post-series depression

Newest response from filtered similarity:  
Top 1 most similar thread's ID: 17tpx8l ; Subject title: I just finished “Crash Landing On You” and I will never be the same.  
Top 2 most similar thread's ID: i42ez5 ; Subject title: How come you started watching it?  
Top 3 most similar thread's ID: kclv6n ; Subject title: Happy Birthday to CLOY!  
Top 4 most similar thread's ID: iy5qeu ; Subject title: Withdrawal, anyone?  
Top 5 most similar thread's ID: u1lawc ; Subject title: Just finished the show…

#### After removing stop words, the top five most similar threads changed, but three of the original top five remained. Considering that there are 3,075 threads in the dataset, this suggests that the similarity results are **fairly consistent** even after stop words are removed. However, the order changed and two new threads appeared in the top five, showing that stop words still have some influence on the cosine similarity scores. Overall, removing stop words seems to preserve the main similarity patterns while allowing the comparison to focus more on meaningful content words.